<header>
    <a href=""><img src="../assets/img/4u-ico-b.png" class="menu-logo"></a>
    <nav class="menu" role="full-horizontal">
        <input type="checkbox" id="button">
        <label for="button" onclick><i class="fa fa-bars"></i></label>
        <ul>
            <li class=""><a href="home.php">Início</a></li>
            <li class=""><a href="">Pessoas</a></li>
            <li><a href="disciplines.php">Disciplinas</a></li>
        </ul>
    </nav>
</header>
